//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewStoreSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int Id { get; set; }
        public System.DateTime fecha { get; set; }
        public string cliente { get; set; }
        public int producto { get; set; }
        public double precio_venta { get; set; }
        public double total { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
